opdreport: Set RestartCause to HostCrash for hardware dump
Set RestartCause to HostCrash when this is a hardware dump (type=1).
This ensures pldmd sets pvm_boot_initiator to "Auto" so that
Auto Power On Restart (APR) correctly re-IPLs the partition after
a system checkstop, even when the partition IPL action is "Hold".

Change-Id: I788b42d2e983f54bcf0a59acc47d243b510a2875
Signed-off-by: Swetha Parasa <parasa.swetha1@ibm.com>

diff --git a/dump/tools/opdump/opdreport b/dump/tools/opdump/opdreport
--- a/dump/tools/opdump/opdreport
+++ b/dump/tools/opdump/opdreport
@@ -182,6 +182,26 @@ function initiate_bmc_dump() {
     fi
 }
 
+# @brief Set RestartCause to HostCrash for hardware dumps
+# This ensures pldmd sets pvm_boot_initiator to "Auto" so that
+# Auto Power On Restart (APR) correctly re-IPLs the partition after
+# a system checkstop, even when the partition IPL action is "Hold".
+function set_restart_cause() {
+    if [[ "$dump_sbe_type" -eq 1 ]]; then
+        busctl set-property \
+            xyz.openbmc_project.State.Host \
+            /xyz/openbmc_project/state/host0 \
+            xyz.openbmc_project.State.Host \
+            RestartCause s \
+            "xyz.openbmc_project.State.Host.RestartCause.HostCrash"
+        if [[ $? -ne $SUCCESS ]]; then
+            echo "$($TIME_STAMP)" "Warning: Failed to set RestartCause to HostCrash"
+        else
+            echo "$($TIME_STAMP)" "RestartCause set to HostCrash for hardware dump"
+        fi
+    fi
+}
+
 # @brief Main function
 function main() {
     initialize
@@ -206,6 +226,8 @@ function main() {
     else
         echo "$($TIME_STAMP)" "Successfully completed"
     fi
+
+    set_restart_cause
 
     initiate_bmc_dump
     return "$SUCCESS"
